// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestApiCourceTurorial.Data;

namespace RestApiCourceTurorial.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("RestApiCourceTurorial.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4e00e4ba-37b1-4c5a-967e-65a70a089422"),
                            Name = "Yuval"
                        },
                        new
                        {
                            Id = new Guid("ace52839-62ef-4e76-b73d-e5b3a33e063a"),
                            Name = "Antwerp"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
